### ISSUE TITLE
sinuous immediately closes upon running

### ISSUE THREAD

**Issue by jat255** [abusch/sinuous#23]
I installed sinuous via the AUR and was excited to give it a try. Unfortunately when I try to run it, it sort of flashes my terminal blank for a split second and then returns back to my prompt.

I tried running with `$ RUST_LOG="sinuous=debug" sinuous`, and the following gets outputted to the log file:

```
2022-04-25T23:08:34.933016Z DEBUG sinuous::sonos: Connecting to provided speakers...
2022-04-25T23:08:34.933201Z DEBUG sinuous::sonos: Discovering speakers...
2022-04-25T23:08:35.282712Z  INFO sinuous::sonos: Found 2 speakers
2022-04-25T23:08:35.282745Z DEBUG sinuous::sonos: Starting sonos loop
```

It looks like it properly discovered my speakers (I have two), but then I guess it just crashes. I don't see any other log or terminal output. Any ideas where to look for what's going wrong?

**Comment by abusch** [comment]
Hi, thanks for the bug report!

It is hard indeed to know what caused the crash as I think at the moment if the main loop fails it prints something to the terminal, which is then immediately cleared and reset... 

I have pushed a small change to send that error to the log file instead. Is there any chance you would be able to compile and try the latest `main` version? If not, I might release a new version as there is a small feature in the pipeline anyway.

**Comment by jat255** [comment]
Ok, I cloned the project down and ran via `cargo run` and got the following:

```
2022-04-26T02:56:46.376689Z DEBUG sinuous::sonos: Connecting to provided speakers...
2022-04-26T02:56:46.376829Z DEBUG sinuous::sonos: Discovering speakers...
2022-04-26T02:56:46.988723Z  INFO sinuous::sonos: Found 2 speakers
2022-04-26T02:56:47.036405Z DEBUG sinuous::sonos: Found 2 groups
2022-04-26T02:56:47.042870Z DEBUG sinuous::sonos: Starting sonos loop
2022-04-26T02:56:47.130400Z  WARN sinuous::sonos: Command channel was closed: exiting...
```

**Comment by abusch** [comment]
So given the lack of helpful message in the logs, it looks like it's not an "expected" error, but something that panics somewhere in the main loop. But of course whatever panic info that's printed gets lost when we reset the terminal 🙄 

I've just pushed some changes to fix that so if you don't mind pulling the latest `main` branch and running `RUST_LOG="sinuous=debug" cargo run --release`, that would be helpful. It should print something in the terminal now if it panics, and generate a report file in `/tmp` that should contain some helpful information 🤞🏻

**Comment by abusch** [comment]
(@jat255 just realized you might not have seen my previous message since I didn't mention you)

**Comment by jat255** [comment]
Ah, yes I had missed this. Apologies. I'm away from home for a few days, but I'll try again over this weekend and try to report back

**Comment by jat255** [comment]
Ok, apologies once again, but I just tried running the latest code and got the following in the error log:

```
 ❯ cat /tmp/report-afa2db0f-7b57-4faf-a034-6d002adbae86.toml 
name = 'sinuous'
operating_system = 'unix:Arch'
crate_version = '0.1.2'
explanation = '''
Panic occurred in file '/home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.18.0/src/widgets/gauge.rs' at line 62
'''
cause = 'Ratio should be between 0 and 1 inclusively.'
method = 'Panic'
backtrace = '''

   0: 0x5587ad4e6cc9 - <unresolved>
   1: 0x5587ad48577e - <unresolved>
   2: 0x5587ad3f952f - <unresolved>
   3: 0x5587ad45776e - <unresolved>
   4: 0x5587ad4289b8 - <unresolved>
   5: 0x5587ad43aee7 - <unresolved>
   6: 0x5587ad41178a - <unresolved>
   7: 0x5587ad47cf43 - <unresolved>
   8: 0x5587ad43a3b9 - <unresolved>
   9: 0x5587ad6936c1 - <unresolved>
  10: 0x5587ad415432 - <unresolved>
  11: 0x7f3fb5332310 - __libc_start_call_main
  12: 0x7f3fb53323c1 - __libc_start_main@GLIBC_2.2.5
  13: 0x5587ad3f2085 - <unresolved>
  14:        0x0 - <unresolved>'''
```

**Comment by jat255** [comment]
On the off chance this was a system package version issue, I did a full system upgrade and tried again. The error text changed slightly, but the general idea is the same:

```
 ❯ cat /tmp/report-52355b6a-58ed-4161-b842-585726ce15db.toml
name = 'sinuous'
operating_system = 'unix:Arch'
crate_version = '0.1.2'
explanation = '''
Panic occurred in file '/home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.18.0/src/widgets/gauge.rs' at line 62
'''
cause = 'Ratio should be between 0 and 1 inclusively.'
method = 'Panic'
backtrace = '''

   0: 0x55cc11b6dcc9 - <unresolved>
   1: 0x55cc11b0c77e - <unresolved>
   2: 0x55cc11a8052f - <unresolved>
   3: 0x55cc11ade76e - <unresolved>
   4: 0x55cc11aaf9b8 - <unresolved>
   5: 0x55cc11ac1ee7 - <unresolved>
   6: 0x55cc11a9878a - <unresolved>
   7: 0x55cc11b03f43 - <unresolved>
   8: 0x55cc11ac13b9 - <unresolved>
   9: 0x55cc11d1a6c1 - <unresolved>
  10: 0x55cc11a9c432 - <unresolved>
  11: 0x7f8628510290 - <unresolved>
  12: 0x7f862851034a - __libc_start_main
  13: 0x55cc11a79085 - <unresolved>
  14:        0x0 - <unresolved>'''
```

**Comment by abusch** [comment]
@jat255 Thanks, this is useful!

The ratio of (elapsed time / track duration), which I assumed should always be between 0 and 1, somehow isn't (not sure why). I've added some code to guard against that, so hopefully that'll fix things for you. Let me know how it goes.

**Comment by jat255** [comment]
Would you look at that, it's working! I think the issue is that I often listen to TuneIn stations and the like, which according to the TUI I'm seeing now, don't have any sort of length defined, so my guess is the ratio was going over 1:

![image](https://user-images.githubusercontent.com/1278301/168932121-4a1021ba-73c3-4798-9d4b-2b9bd58ebe4b.png)

Thanks again for your help debugging.

**Comment by abusch** [comment]
Glad it worked! I've just cut a release and updated the AUR package.
