### ISSUE TITLE
UPnP discovery for Sonos devices returned non-Sonos devices

### ISSUE THREAD

**Issue by mattydebie** [abusch/sinuous#93]
When installing from the AUR, and trying to run it the first time I get the following log in /tmp/sinuous.log:
```
2023-08-02T13:02:02.336207Z ERROR sinuous::sonos: Sonos error err=UPnP discovery for Sonos devices returned non-Sonos device
```

**Comment by abusch** [comment]
Thanks for the report. It was an issue with a dependency (`sonor`) which is now fixed. I've just pushed a new release.
